import '@/styles/globals.css';
import type { Metadata } from 'next'
import localFont from 'next/font/local';

const pokeSolid = localFont({
  src: '../public/fonts/pokemon-solid.ttf',
  variable: '--font-pokeSolid'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${pokeSolid.variable} bg-[#2C7ABC]`}>{children}</body>
    </html>
  )
}
